version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: #SUASENHA
      POSTGRES_DB: dscatalog
    networks:
      - reinan-network
  app:
     image: reinan07/dscatalog
     restart: always
     build: ./backend
     working_dir: /backend
     environment:
       APP_PROFILE: prod
       DB_URL: jdbc:postgresql://db:5432/dscatalog
       DB_USERNAME: postgres
       DB_PASSWORD: #SUASENHA
       SECRET_KEY: secretKey
     ports:
       - "80:80"
     depends_on:
       - db
     networks:
       - reinan-network

networks:
    reinan-network:
        driver: bridge

