version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Teste3345#
      POSTGRES_DB: dscatalog
    networks:
      - app-network

  app:
     depends_on:
      - db

     image: reinan07/dscatalog
     restart: always
     build: ./backend
     working_dir: /backend
     environment:
       APP_PROFILE: prod
       DB_URL: jdbc:postgresql://db:5432/dscatalog
       DB_USERNAME: postgres
       DB_PASSWORD: Teste3345#
       SECRET_KEY: secretKey
     ports:
       - "8080:8080"

     networks:
       - app-network

networks:
    app-network:
        driver: bridge

