spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

    h2:
      console:
        enabled: true
        path: /h2-console

security:
  jwt:
       secret: secretkey
       accessTokenExpirationMs: 3600000
       refreshTokenExpirationMs: 86400000
