spring:
  datasource:
  
    url: ${DB_URL:jdbc:postgresql://db:5432/dscatalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Teste3345#}
    driver-class-name: org.postgresql.Driver

security:
  jwt:
       secret: ${SECRET_KEY:secretkey}
       accessTokenExpirationMs: 3600000
       refreshTokenExpirationMs: 86400000

