spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

security:
  jwt:
       secret: ${SECRET_KEY:secretkey}
       accessTokenExpirationMs: 3600000
       refreshTokenExpirationMs: 86400000

