spring:
  datasource:
    url: jdbc:h2:mem:testdbapplication-test.yml
    username: sa
    password:
    driver-class-name: org.h2.Driver

security:
  jwt:
       secret:
       accessTokenExpirationMs: 3600000
       refreshTokenExpirationMs: 86400000

flyway:
    locations: classpath:/db/migration
