spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dscatalog
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

security:
  jwt:
       secret:
       accessTokenExpirationMs: 3600000
       refreshTokenExpirationMs: 86400000

