
name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
        - "main" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
   
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application jar
      working-directory: ./InventoryManagementAPI/backend
      run: mvn package clean

    - name: Docker Compose Build
      working-directory: ./InventoryManagementAPI
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: 
      
        docker tag ${{ DOCKER_USERNAME }}/dscatalog:lastet  ${{ DOCKER_USERNAME }}/dscatalog:${{ github.run_id }}
        
        docker push ${{ DOCKER_USERNAME }}/dscatalog:${{ github.run_id }}
        docker push ${{ DOCKER_USERNAME }}/dscatalog:lastet
