
name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
        - "main" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
   
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application jar
      working-directory: ./InventoryManagementAPI/backend
      run: mvn package clean

    - name: Docker Compose Build
      working-directory: ./InventoryManagementAPI
      run: docker compose build

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
